# Generated by Django 2.0.3 on 2018-03-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elmenu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='pizza', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='not entered', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='pizza',
            field=models.CharField(default="domino's", max_length=100),
            preserve_default=False,
        ),
    ]
