# Generated by Django 2.0.3 on 2018-03-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elmenu', '0002_auto_20180331_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='OrderHist',
        ),
    ]
